flowchart TD
    %% =====================
    %% _rotate_index()
    %% =====================
    R1[Start_rotate_index] --> S1[Increment current_index modulo total keys] --> T1[End_rotate_index] --> T

    T@{ shape: summary}
