# Translation Framework Configuration
api:
  url: "https://openrouter.ai/api/v1/chat/completions"
  max_retries: 3
  backoff_base: 2.0
  max_requests_per_minute: 20

translation:
  model: "google/gemini-2.0-flash-exp:free"
  temperature: 1
  presence_penalty: 0.0
  frequency_penalty: 0.0
  top_p: 1
  top_k: 50
  min_p: 0
  top_a: 1
  repetition_penalty: 1.2

scheduling:
  job_delay: 10.0
  max_concurrent: 100

validation:
  strict_json: true
  allow_partial: false

standardization:
  default_format: "json"
  auto_convert: true